### ISSUE TITLE
logos on project detail page are not well aligned kindly check.

### ISSUE THREAD

**Issue by Labohkip81** [Labohkip81/labohkip81.github.io#15]
@Musyimi97

**Comment by Musyimi97** [comment]
On it.. @Labohkip81

**Comment by Musyimi97** [comment]
![screenshot](https://user-images.githubusercontent.com/39317926/77089084-67b59680-6a16-11ea-846b-8224d2f53a64.png)
 
the header images @Labohkip81

**Comment by Labohkip81** [comment]
for the same page?

**Comment by Musyimi97** [comment]
its done...
![screeeeeeeeeeeeba](https://user-images.githubusercontent.com/39317926/77106543-51b4cf80-6a30-11ea-85d8-b4b1e987d17e.png)
